### ISSUE TITLE
Zone holding bitmap

### ISSUE THREAD

**Issue by blhoward2** [lurgh/infinitive#1]
Hey there, I'm actually re-writing infinitive in node.js, while trying to improve some things. If you wouldn't mind helping me a bit. Are you seeing the zones holding bitmap actually change when you put a zone into holding on the thermostat? My system isn't zoned but that byte (11) in the 3b03 table is always 0 on mine. While I don't have a zoned system, I'm trying to write a complete driver.

Also, what do you see in byte 37 in 3b03 when you put a zone other than zone 1 into holding? That appears to be a 0/1 field showing whether zone 1 is in holding on mine, but I'm not sure what the point of that would be if other zones could also be holding... It just seems unnecessary given that there is a hold duration byte.

**Comment by lurgh** [comment]
Yes, byte 11 is 0x00 normally, 0x01 when zone 1 is in HOLD, 0x02 when zone 2 is in HOLD, etc.

Example: set zone 2 into HOLD, and then unset it:
*** [Dec 20 16:48:22] 2001 -> 9201: RESPONSE 003b030300000000030303030303**02**494900000000000052510000000000002d2d2d2d2d2d2d2d000000000000000000000000000000000000446f776e73746169727320005570737461697273202020005a4f4e4520332020202020005a4f4e4520342020202020005a4f4e4520352020202020005a4f4e4520362020202020005a4f4e4520372020202020005a4f4e452038202020202000
    [Dec 20 16:48:28] 2001 -> 9201: RESPONSE 003b030300000000030303030303**00**494900000000000052510000000000002d2d2d2d2d2d2d2d000000000000000000000000000000000000446f776e73746169727320005570737461697273202020005a4f4e4520332020202020005a4f4e4520342020202020005a4f4e4520352020202020005a4f4e4520362020202020005a4f4e4520372020202020005a4f4e452038202020202000

Regarding byte 37, what you're saying suggests that you may be confusing HOLD mode with a temporary setpoint override.  I had the same confusion at first because the tstat shows the word HOLD in both cases but it's actually a different state.  If you press the HOLD button on the tstat it will show "Now on HOLD" (with no timer) and you should see the per-zone bit flag set in byte 11.  If instead you change the setpoint, it will say "HOLD for 2:00" and this will set the per-zone bit flag in byte 37, and show the remaining number of minutes (0x0078 = 120) in the per-zone override time (bytes 38-39 for zone 1).  Does that make more sense?

**Comment by blhoward2** [comment]
Thanks, that helps a lot. You don't by chance have a real SAM do you?

**Comment by lurgh** [comment]
No I do not have a real SAM.  All my work has been based on the prior work that went into infinitive, plus my own experimentation.

**Comment by blhoward2** [comment]
Thanks for the help!
